//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Datos
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_a97d9e_zonamovilEntities : DbContext
    {
        public db_a97d9e_zonamovilEntities()
            : base("name=db_a97d9e_zonamovilEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categoria> Categoria { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<DetalleFacturaCompra> DetalleFacturaCompra { get; set; }
        public virtual DbSet<DetalleFacturaVenta> DetalleFacturaVenta { get; set; }
        public virtual DbSet<DetallePedidoVenta> DetallePedidoVenta { get; set; }
        public virtual DbSet<FacturaCompra> FacturaCompra { get; set; }
        public virtual DbSet<FacturaVenta> FacturaVenta { get; set; }
        public virtual DbSet<Marca> Marca { get; set; }
        public virtual DbSet<PedidoVenta> PedidoVenta { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<Proveedor> Proveedor { get; set; }
        public virtual DbSet<Rol> Rol { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
    
        public virtual ObjectResult<spObtenerDetalleProducto_Result> spObtenerDetalleProducto(Nullable<int> idProducto)
        {
            var idProductoParameter = idProducto.HasValue ?
                new ObjectParameter("IdProducto", idProducto) :
                new ObjectParameter("IdProducto", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spObtenerDetalleProducto_Result>("spObtenerDetalleProducto", idProductoParameter);
        }
    
        public virtual ObjectResult<spInfoFacturaVenta_Result> spInfoFacturaVenta()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spInfoFacturaVenta_Result>("spInfoFacturaVenta");
        }
    
        public virtual ObjectResult<spDetalleFacturaVenta_Result> spDetalleFacturaVenta(Nullable<int> nf)
        {
            var nfParameter = nf.HasValue ?
                new ObjectParameter("nf", nf) :
                new ObjectParameter("nf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDetalleFacturaVenta_Result>("spDetalleFacturaVenta", nfParameter);
        }
    
        public virtual ObjectResult<spBuscarFacturaVentaPorRangoFechas_Result> spBuscarFacturaVentaPorRangoFechas(Nullable<System.DateTime> f1, Nullable<System.DateTime> f2)
        {
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("f1", f1) :
                new ObjectParameter("f1", typeof(System.DateTime));
    
            var f2Parameter = f2.HasValue ?
                new ObjectParameter("f2", f2) :
                new ObjectParameter("f2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscarFacturaVentaPorRangoFechas_Result>("spBuscarFacturaVentaPorRangoFechas", f1Parameter, f2Parameter);
        }
    
        public virtual ObjectResult<spBuscarFacturaVentaPorRangoFechas_Result> spBuscarFacturaVentaPorRangoFechas1(Nullable<System.DateTime> f1, Nullable<System.DateTime> f2)
        {
            var f1Parameter = f1.HasValue ?
                new ObjectParameter("f1", f1) :
                new ObjectParameter("f1", typeof(System.DateTime));
    
            var f2Parameter = f2.HasValue ?
                new ObjectParameter("f2", f2) :
                new ObjectParameter("f2", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spBuscarFacturaVentaPorRangoFechas_Result>("spBuscarFacturaVentaPorRangoFechas1", f1Parameter, f2Parameter);
        }
    
        public virtual ObjectResult<spDetalleFacturaVenta_Result> spDetalleFacturaVenta1(Nullable<int> nf)
        {
            var nfParameter = nf.HasValue ?
                new ObjectParameter("nf", nf) :
                new ObjectParameter("nf", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDetalleFacturaVenta_Result>("spDetalleFacturaVenta1", nfParameter);
        }
    }
}
